### PR TITLE
Bump iree to 20231130.724

### PR DESCRIPTION
**Pull request by AmosLewis**
To solve the issue https://github.com/nod-ai/SHARK-Turbine/issues/110

### CODE REVIEW

**Comment by stellaraccident** [comment]
(in the future, more descriptive PR title/description please)

**Comment by AmosLewis** [comment]
The bumping torch-mlir will break the llama test, where some more ops need to supported in linalg:
https://gist.github.com/AmosLewis/5eb8e66e899257e7456af738269b91bf

**Comment by stellaraccident** [comment]
I don't really know where we got this particular test from and it is not exercising our production path. If we most, we can xfail it and fix forward.

**Comment by AmosLewis** [comment]
> I don't really know where we got this particular test from and it is not exercising our production path. If we most, we can xfail it and fix forward.

It's from here. I think we should xfail it https://github.com/nod-ai/SHARK-Turbine/pull/36

**Comment by stellaraccident** [comment]
Can we add an issue to fix it when we do that and make sure to work it. It is important to have some generality in coverage, but this stuff is new enough I don't think we need to stop the train for it.

**Comment by AmosLewis** [comment]
> Can we add an issue to fix it when we do that and make sure to work it. It is important to have some generality in coverage, but this stuff is new enough I don't think we need to stop the train for it.

Here we go https://github.com/nod-ai/SHARK-Turbine/issues/221

**Comment by AmosLewis** [comment]
One more test error with **uninitialized=True**. https://github.com/nod-ai/SHARK-Turbine/blob/0c658bd6557aa27a1479d8ba9acbae34e5527379/tests/aot/globals_test.py#L351
This was added https://github.com/nod-ai/SHARK-Turbine/pull/201, that was supported in 20231121.715, but with 20231130.724, it has a regression in iree. The unintialized=True support patch might has been reverted in IREE? 
```
iree.compiler._mlir_libs._site_initialize.<locals>.MLIRError: Unable to parse attribute:
error: "#util.uninitialized : tensor<30x20xf32>":1:7: unknown attribute `uninitialized` in dialect `util`
```

**Comment by stellaraccident** [comment]
Something is wrong -- this route could not be happening with a certain in the last two weeks. We need to look at iree and see why it seems to be going back in time.

**Comment by stellaraccident** [comment]
> One more test error with **uninitialized=True**.
> 
> https://github.com/nod-ai/SHARK-Turbine/blob/0c658bd6557aa27a1479d8ba9acbae34e5527379/tests/aot/globals_test.py#L351
> 
> 
> This was added #201, that was supported in 20231121.715, but with 20231130.724, it has a regression in iree. The unintialized=True support patch might has been reverted in IREE?
> ```
> iree.compiler._mlir_libs._site_initialize.<locals>.MLIRError: Unable to parse attribute:
> error: "#util.uninitialized : tensor<30x20xf32>":1:7: unknown attribute `uninitialized` in dialect `util`
> ```

Where are you seeing this? I think it must be testing an old wheel somehow.

**Comment by AmosLewis** [comment]
> Where are you seeing this? I think it must be testing an old wheel somehow.

It's on my local machine. You are right. I just double-checked it and it tried to use my old iree_build.

**Review by stellaraccident — APPROVED** [review]

**Pull request merged**
